### ISSUE TITLE
Configure script fails on Manjaro linux

### ISSUE THREAD

**Issue by supagu** [crosswire/xiphos#818]
I am getting the same error this person is getting trying to build and run xiphos:
https://sourceforge.net/p/gnomesword/mailman/message/32281267/

`[fabian@fabian-laptop xiphos]$ ./waf configure --prefix=/usr --debug-level=optimized
Linux detected 
Traceback (most recent call last):
  File "/home/fabian/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Utils.py", line 445, in recurse
    txt=readf(file_path,m='rU')
  File "/home/fabian/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Utils.py", line 408, in readf
    f=open(fname,m)
FileNotFoundError: [Errno 2] No such file or directory: '/home/fabian/xiphos/wscript_configure'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./waf", line 154, in <module>
    Scripting.prepare(t, cwd, VERSION, wafdir)
  File "/home/fabian/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Scripting.py", line 105, in prepare
    prepare_impl(t,cwd,ver,wafdir)
  File "/home/fabian/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Scripting.py", line 98, in prepare_impl
    main()
  File "/home/fabian/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Scripting.py", line 133, in main
    fun(ctx)
  File "/home/fabian/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Scripting.py", line 172, in configure
    conf.sub_config([''])
  File "/home/fabian/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Configure.py", line 107, in sub_config
    self.recurse(k,name='configure')
  File "/home/fabian/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Utils.py", line 460, in recurse
    f(self)
  File "/home/fabian/xiphos/wscript", line 165, in configure
    conf.check_tool('nothreads', tooldir=_tooldir)
  File "/home/fabian/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Configure.py", line 97, in check_tool
    module=Utils.load_tool(tool,tooldir)
  File "/home/fabian/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Utils.py", line 400, in load_tool
    return __import__(tool)
  File "./waffles/nothreads.py", line 24
    except Exception, e:
                    ^
SyntaxError: invalid syntax
[fabian@fabian-laptop xiphos]$ 
`

**Comment by karlkleinpaste** [comment]
please see my comment at the end of that older bug report. the same thought still applies -- we have nothing named wscript_configure in our source tree, so the idea that your instance of waf is looking for it tells me that your waf environment is not correct. and the same general guess also still applies, that you probably are missing some aspect of the build system in order to make this work. manjaro is the only linux distribution for which i've ever seen this sort of waf failure. notably, the existing waf configuration builds readily for fedora/rhel/centos and ubuntu environments.

i will leave this open for a little while in hope of providing a bit of help, but from where we sit, this isn't a xiphos issue, it's an insufficient-tools-at-the-ready issue.
