### ISSUE TITLE
doesn't compile on ubuntu 18.04

### ISSUE THREAD

**Issue by BlackArbsCEO** [crosswire/xiphos#914]
Hi while trying to compile on Ubuntu 18.04 I ran into a few issues. First in the `./xiphos/waffles/nothreads.py` I had to fix a couple syntax errors with `Exception, e:` to `Exception as e:`. Then after installing `intltool` I got the following error:

```
Linux detected 
Check for program g++ or c++             : /usr/bin/g++ 
Check for program cpp                    : /usr/bin/cpp 
Check for program ar                     : /usr/bin/ar 
Check for program ranlib                 : /usr/bin/ranlib 
Check for program gcc or cc              : /usr/bin/gcc 
Check for program msgfmt                 : /usr/bin/msgfmt 
Check for program intltool-merge         : /usr/bin/intltool-merge 
Checking for header locale.h             : Traceback (most recent call last):
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Utils.py", line 445, in recurse
    txt=readf(file_path,m='rU')
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Utils.py", line 408, in readf
    f=open(fname,m)
FileNotFoundError: [Errno 2] No such file or directory: '/media/bcr/HDD/Bible_Notes/xiphos/wscript_configure'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./waf", line 154, in <module>
    Scripting.prepare(t, cwd, VERSION, wafdir)
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Scripting.py", line 105, in prepare
    prepare_impl(t,cwd,ver,wafdir)
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Scripting.py", line 98, in prepare_impl
    main()
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Scripting.py", line 133, in main
    fun(ctx)
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Scripting.py", line 172, in configure
    conf.sub_config([''])
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Configure.py", line 107, in sub_config
    self.recurse(k,name='configure')
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Utils.py", line 460, in recurse
    f(self)
  File "/media/bcr/HDD/Bible_Notes/xiphos/wscript", line 172, in configure
    conf.check_tool('intltool')
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Configure.py", line 103, in check_tool
    if type(func)is type(find_file):func(self)
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Tools/intltool.py", line 88, in detect
    conf.check(header_name='locale.h')
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Tools/config_c.py", line 321, in check
    ret=self.run_c_code(*k,**kw)
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Tools/config_c.py", line 379, in run_c_code
    bld.compile()
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Build.py", line 172, in compile
    self.save()
  File "/media/bcr/HDD/Bible_Notes/xiphos/.waf3-1.5.15-49b2085e76313a25671ed8aa1c64079f/wafadmin/Build.py", line 116, in save
    cPickle.dump(data,file)
AttributeError: Can't pickle local object 'BuildContext.__init__.<locals>.node_class'

```

**Comment by domcorbex** [comment]
Have you tried to build xiphos with CMake instead of Waf?

**Comment by karlkleinpaste** [comment]
out of date since waf is replaced by cmake.
